{"name": "test_unauthorized_access", "status": "passed", "description": "Проверка отказа в доступе при использовании недействительного API ключа.", "steps": [{"name": "Получение задачи по ID: '901310108562'", "status": "passed", "steps": [{"name": "GET /task/901310108562", "status": "passed", "start": 1745078826109, "stop": 1745078826353}], "parameters": [{"name": "task_id", "value": "'901310108562'"}], "start": 1745078826109, "stop": 1745078826353}], "start": 1745078826109, "stop": 1745078826353, "uuid": "db49bf4b-6e96-44f7-b864-06994db3f312", "historyId": "9cba1e9a7f27cb6079dcba3f607f479d", "testCaseId": "9cba1e9a7f27cb6079dcba3f607f479d", "fullName": "tests.api.test_tasks#test_unauthorized_access", "labels": [{"name": "feature", "value": "Авторизация"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "host", "value": "DESKTOP-77BDOFA"}, {"name": "thread", "value": "12420-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}