{"name": "test_update_task_negative", "status": "passed", "description": "Негативный тест: передача некорректных данных при обновлении задачи.", "steps": [{"name": "Обновление задачи по ID: '86a839d10'", "status": "passed", "parameters": [{"name": "task_id", "value": "'86a839d10'"}, {"name": "task_update", "value": "'invalid_payload'"}], "start": 1745261073205, "stop": 1745261073286}], "start": 1745261073205, "stop": 1745261073286, "uuid": "3f3aad0b-58e3-4c55-a902-de044734ea0e", "historyId": "fe5e41104959de7eee0a8bdfa066bd06", "testCaseId": "fe5e41104959de7eee0a8bdfa066bd06", "fullName": "tests.api.test_tasks#test_update_task_negative", "labels": [{"name": "feature", "value": "Задачи"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "host", "value": "DESKTOP-77BDOFA"}, {"name": "thread", "value": "7828-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}