{"name": "test_create_task_negative[task_data5-404-object_not_found]", "status": "failed", "statusDetails": {"message": "AssertionError: Expected 404, got 400\nassert 400 == 404\n +  where 400 = <Response [400]>.status_code", "trace": "tests\\api\\test_tasks.py:119: in test_create_task_negative\n    assert response.status_code == expected_status, (\nE   AssertionError: Expected 404, got 400\nE   assert 400 == 404\nE    +  where 400 = <Response [400]>.status_code"}, "steps": [{"name": "Создание задачи в списке с ID: 'invalid_list_123'", "status": "passed", "steps": [{"name": "POST /list/invalid_list_123/task", "status": "passed", "start": 1745078837934, "stop": 1745078838011}], "parameters": [{"name": "list_id", "value": "'invalid_list_123'"}, {"name": "task_data", "value": "{}"}], "start": 1745078837934, "stop": 1745078838011}], "parameters": [{"name": "task_data", "value": "{'list_id': 'invalid_list_123'}"}, {"name": "expected_status", "value": "404"}, {"name": "expected_ecode", "value": "'object_not_found'"}], "start": 1745078837934, "stop": 1745078838011, "uuid": "b939aa6c-245c-4d82-b3d2-c2ef713545f1", "historyId": "ca764a4b2a8aee5d3b3a092e8c19937b", "testCaseId": "e68a266bd94a31c77d043e15942220bb", "fullName": "tests.api.test_tasks#test_create_task_negative", "labels": [{"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "host", "value": "DESKTOP-77BDOFA"}, {"name": "thread", "value": "12420-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}